### ISSUE TITLE
Непрерывная интеграция на базе circleCI

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/zold-lazy-node#1]
Говорят он стал быстрый и модный. Хотя и раньше был быстрым.

**Comment by 0pdd** [comment]
@DronMDF 2 puzzles [#10](https://github.com/DronMDF/zold-lazy-node/issues/10), [#9](https://github.com/DronMDF/zold-lazy-node/issues/9) are still not solved.

**Comment by 0pdd** [comment]
@DronMDF 2 puzzles [#10](https://github.com/DronMDF/zold-lazy-node/issues/10), [#26](https://github.com/DronMDF/zold-lazy-node/issues/26) are still not solved; solved: [#9](https://github.com/DronMDF/zold-lazy-node/issues/9).
