### ISSUE TITLE
Не работает отсечение старых Score.

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/zold-lazy-node#101]
На главной странице висит Score
```json
{"farm":{"current":[]},"score":{"host":"37.230.116.39","invoice":"5dwXZhmZ@cc53e22229564de6","port":4096,"strength":6,"suffixes":["gbfQwBh","JPh7KTh","bXf9vJR","fY3Ti6g","VPytDxc","HwWpf9i","hfbdprU","gnpC9He","bLVs3Ld","XaNvSuN","1Gxyk3m","BFX8ZeP","87BpsTJ","cg78DyK","abVrE3p","XTNG1yv"],"time":"2018-08-02T13:53:10Z"},"version":"0.14.13"}
```

Хотя время на сервере уже ушло более чем на сутки вперед
```
$ date -u
Fri Aug  3 15:02:50 UTC 2018
```

База данных при этом выглядит так:
```
select * from Score;
1|2018-08-02 13:53:10.000000|37.230.116.39|4096|5dwXZhmZ@cc53e22229564de6|6
2|2018-08-03 07:30:55.000000|37.230.116.39|4096|z88E3jSA@cc53e22229564de6|6
```

**Comment by DronMDF** [comment]
Тут видимо что-то с зонами... или с урлами (не те урлы дергаем?)
Сейчас открылся с новым Score, значит старый всетаки заэкспайрился.
Но что-то он заэкспайрился немного позже, чем нужно.

**Comment by DronMDF** [comment]
На часах 7 августа, 12:24 MSK, 
Это Вт авг  7 09:24:52 UTC 2018 

Сервер продолжает отдавать старый Score
{"farm":{"current":[]},"score":{"host":"37.230.116.39","invoice":"HdssRDl6@cc53e22229564de6","port":4096,"strength":6,"suffixes":["P45sTbY","XchV45N","G3yTpck","28U4DQJ","YphrHS2","YPW7Nq8","XMksSoz","PwQv6Df","iFsNJuH","R6ACYyr","ZxYdd8G","81GE5fQ","c8Rrckd","2XtsRuF","bJhJoAX","a3jG8BN"],"time":"2018-08-06T06:45:48Z"},"version":"0.14.13"}

**Comment by DronMDF** [comment]
В 13:49 по MSK Score изменился.
{"farm":{"current":[]},"score":{"host":"37.230.116.39","invoice":"v54Awb4p@cc53e22229564de6","port":4096,"strength":6,"suffixes":["3rrzBWT","ZJ4tmAo","99o21gV","C7JguWq","YzfkAhE","dmuZfW3","7gbktqG","8DquPg8","XsNWSE6","ECt9iwW","BMxJEvG","3KW4rCw","YqbL4bj","aNyXBVK","QkDuFEH","AWPBxKc"],"time":"2018-08-06T22:46:02Z"},"version":"0.14.13"}

**Comment by DronMDF** [comment]
Проблема видимо где-то здесь..
Потому что второй Score тоже создан не через 12 часов, а через 16...
Видимо нужно выкинуть этот класс нафиг, и сделать его работающим с любыми Score. (отвязать его от БД).
И перенести в zold.

```python3
class DbNewerThenScores:
        def __iter__(self):
                since = datetime.now() - self.interval
                return (DbScore(s) for s in Score.query.filter(Score.time >= since))
```

**Comment by 0pdd** [comment]
@DronMDF the puzzle [#112](https://github.com/DronMDF/zold-lazy-node/issues/112) is still not solved.
