### ISSUE TITLE
Обновление информации о remote через запрос индекса...

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/zold-lazy-node#105]
Утилита сможет обращаться к серверу впихивая в заголовок Score разных узлов, сервер будет прикапывать их у себя.

Но при выводе стоит фильтровать только узлы с актуальным Score, не менее 3.
При этом мертвые узлы будут оседать в недрах БД и не будут анонсироваться.

**Comment by 0pdd** [comment]
@DronMDF 3 puzzles [#108](https://github.com/DronMDF/zold-lazy-node/issues/108), [#109](https://github.com/DronMDF/zold-lazy-node/issues/109), [#110](https://github.com/DronMDF/zold-lazy-node/issues/110) are still not solved.

**Comment by 0pdd** [comment]
@DronMDF 2 puzzles [#109](https://github.com/DronMDF/zold-lazy-node/issues/109), [#110](https://github.com/DronMDF/zold-lazy-node/issues/110) are still not solved; solved: [#108](https://github.com/DronMDF/zold-lazy-node/issues/108).
