### ISSUE TITLE
Майнер должен обновлять списки узлов на сервере

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/zold-lazy-node#107]
Майнер не самое подходящее слово... Лучше подойдет слово воркер? slave... zlave - о да...

**Comment by 0pdd** [comment]
@DronMDF 2 puzzles [#121](https://github.com/DronMDF/zold-lazy-node/issues/121), [#141](https://github.com/DronMDF/zold-lazy-node/issues/141) are still not solved; solved: [#122](https://github.com/DronMDF/zold-lazy-node/issues/122).

**Comment by 0pdd** [comment]
@DronMDF 4 puzzles [#238](https://github.com/DronMDF/zold-lazy-node/issues/238), [#239](https://github.com/DronMDF/zold-lazy-node/issues/239), [#240](https://github.com/DronMDF/zold-lazy-node/issues/240), [#241](https://github.com/DronMDF/zold-lazy-node/issues/241) are still not solved; solved: [#121](https://github.com/DronMDF/zold-lazy-node/issues/121), [#122](https://github.com/DronMDF/zold-lazy-node/issues/122), [#141](https://github.com/DronMDF/zold-lazy-node/issues/141).
