### ISSUE TITLE
502 Bad Gateway After deploy new version

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/zold-lazy-node#113]

**Comment by DronMDF** [comment]
Не понятно в чем причина...
Ничего не менял.
Просто последовательно перезапустил все сервисы.

Возможно nginx не перезапускается?
Сделать ему принудительный перезапуск?

**Comment by DronMDF** [comment]
service gunicorn restart не работает как надо.
stop/start и сайт отзывается.

**Comment by 0pdd** [comment]
@DronMDF the puzzle [#136](https://github.com/DronMDF/zold-lazy-node/issues/136) is still not solved.

**Comment by DronMDF** [comment]
Возможно после накатывания uwsgi система будет вести себя лучше.

**Comment by DronMDF** [comment]
sudo uwsgi --http-socket 0.0.0.0:8000 --plugin python35 --pythonpath /usr/share/zold --chdir /usr/share/zold --wsgi-file node/app.py --callable APP
Так сервер отзывается... без nginx...
