### ISSUE TITLE
zln.py:28: Функция слишком длинная, необходима реорганизация

### ISSUE THREAD

**Issue by 0pdd** [DronMDF/zold-lazy-node#121]
The puzzle `107-2447be54` from #107 has to be resolved:

https://github.com/DronMDF/zold-lazy-node/blob/ba188bebda32f429dbfb01b366389825a424aba7/zln/zln.py#L28-L28

The puzzle was created by Andrey Valyaev on 23-Aug-18. 

Estimate: 0 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by DronMDF** [comment]
Заодно наметить точки расширения в плане нового tasks api.

**Comment by 0pdd** [comment]
The puzzle `107-2447be54` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 4 puzzles [#238](https://github.com/DronMDF/zold-lazy-node/issues/238), [#239](https://github.com/DronMDF/zold-lazy-node/issues/239), [#240](https://github.com/DronMDF/zold-lazy-node/issues/240), [#241](https://github.com/DronMDF/zold-lazy-node/issues/241) are still not solved.
