### ISSUE TITLE
Недостающие кошельки для remotes в /tasks 

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/zold-lazy-node#139]
Добавляется специальная таска
type: wallet
id:xxxxxxx
prefix: xxxx <- опциональное поле

Нужен для того, чтобы боты нашли на других серверах этот кошелек и залили его сюда.
При поиске кошелька, если указан prefix - нужно проверять, что проверка префикса проходит.

**Comment by 0pdd** [comment]
@DronMDF 2 puzzles [#146](https://github.com/DronMDF/zold-lazy-node/issues/146), [#147](https://github.com/DronMDF/zold-lazy-node/issues/147) are still not solved.

**Comment by 0pdd** [comment]
@DronMDF 6 puzzles [#152](https://github.com/DronMDF/zold-lazy-node/issues/152), [#153](https://github.com/DronMDF/zold-lazy-node/issues/153), [#154](https://github.com/DronMDF/zold-lazy-node/issues/154), [#155](https://github.com/DronMDF/zold-lazy-node/issues/155), [#156](https://github.com/DronMDF/zold-lazy-node/issues/156), [#157](https://github.com/DronMDF/zold-lazy-node/issues/157) are still not solved; solved: [#146](https://github.com/DronMDF/zold-lazy-node/issues/146), [#147](https://github.com/DronMDF/zold-lazy-node/issues/147).

**Comment by 0pdd** [comment]
@DronMDF 6 puzzles [#152](https://github.com/DronMDF/zold-lazy-node/issues/152), [#153](https://github.com/DronMDF/zold-lazy-node/issues/153), [#155](https://github.com/DronMDF/zold-lazy-node/issues/155), [#156](https://github.com/DronMDF/zold-lazy-node/issues/156), [#157](https://github.com/DronMDF/zold-lazy-node/issues/157), [#160](https://github.com/DronMDF/zold-lazy-node/issues/160) are still not solved; solved: [#146](https://github.com/DronMDF/zold-lazy-node/issues/146), [#147](https://github.com/DronMDF/zold-lazy-node/issues/147), [#154](https://github.com/DronMDF/zold-lazy-node/issues/154).

**Comment by 0pdd** [comment]
@DronMDF 2 puzzles [#152](https://github.com/DronMDF/zold-lazy-node/issues/152), [#226](https://github.com/DronMDF/zold-lazy-node/issues/226) are still not solved; solved: [#146](https://github.com/DronMDF/zold-lazy-node/issues/146), [#147](https://github.com/DronMDF/zold-lazy-node/issues/147), [#153](https://github.com/DronMDF/zold-lazy-node/issues/153), [#154](https://github.com/DronMDF/zold-lazy-node/issues/154), [#155](https://github.com/DronMDF/zold-lazy-node/issues/155), [#156](https://github.com/DronMDF/zold-lazy-node/issues/156), [#157](https://github.com/DronMDF/zold-lazy-node/issues/157), [#160](https://github.com/DronMDF/zold-lazy-node/issues/160), [#unknown](), [#unknown](), [#unknown](), [#unknown](), [#unknown](), [#unknown]().
