### ISSUE TITLE
ansible скрипт для разворачивания сервера

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/zold-lazy-node#16]

**Comment by DronMDF** [comment]
В интернетах пишут, что gunicorn сейчас рулит и бибикает.
Вот здесь написано, как связать nginx с gunicorn(в виде сервиса)
Правда здесь написано про django, но это не так принципиально.
https://www.digitalocean.com/community/tutorials/how-to-set-up-django-with-postgres-nginx-and-gunicorn-on-ubuntu-16-04

**Comment by 0pdd** [comment]
@DronMDF 2 puzzles [#39](https://github.com/DronMDF/zold-lazy-node/issues/39), [#40](https://github.com/DronMDF/zold-lazy-node/issues/40) are still not solved.

**Comment by 0pdd** [comment]
@DronMDF 3 puzzles [#103](https://github.com/DronMDF/zold-lazy-node/issues/103), [#104](https://github.com/DronMDF/zold-lazy-node/issues/104), [#39](https://github.com/DronMDF/zold-lazy-node/issues/39) are still not solved; solved: [#40](https://github.com/DronMDF/zold-lazy-node/issues/40).
