### ISSUE TITLE
Дублирование кода при формировании актуального score

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/zold-lazy-node#175]

**Comment by 0pdd** [comment]
@DronMDF 3 puzzles [#227](https://github.com/DronMDF/zold-lazy-node/issues/227), [#228](https://github.com/DronMDF/zold-lazy-node/issues/228), [#230](https://github.com/DronMDF/zold-lazy-node/issues/230) are still not solved; solved: [#unknown]().
