### ISSUE TITLE
Контроль стиля

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/zold-lazy-node#2]
Но отступы табуляциями.
Необходимо прикрутить к CI.

**Comment by 0pdd** [comment]
@DronMDF the puzzle [#12](https://github.com/DronMDF/zold-lazy-node/issues/12) is still not solved.

**Comment by 0pdd** [comment]
@DronMDF 2 puzzles [#14](https://github.com/DronMDF/zold-lazy-node/issues/14), [#15](https://github.com/DronMDF/zold-lazy-node/issues/15) are still not solved; solved: [#12](https://github.com/DronMDF/zold-lazy-node/issues/12).

**Comment by 0pdd** [comment]
@DronMDF the puzzle [#15](https://github.com/DronMDF/zold-lazy-node/issues/15) is still not solved; solved: [#12](https://github.com/DronMDF/zold-lazy-node/issues/12), [#14](https://github.com/DronMDF/zold-lazy-node/issues/14).
