### ISSUE TITLE
Почему-то Wanted забивается транзакциями по кошельку 221255bc9af7baec

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/zold-lazy-node#215]
Хотя этот кошелек загружен...

**Comment by DronMDF** [comment]
Возможно, транзакции не вычищаются из Wanted, если кошелек залился?

НО в кошельке я не вижу этих транзакций.
Возможно они потеряны навсегда.

Поэтому необходимо видимо, при любой заливке кошелька - сносить из wanted все, что там храниться.

Но тогда мне не понятно, зачем мне хранить в Wanted кучу запросов? Если достаточно одного?
Может быть мне просто смотреть - если данный кошелек уже упоминается в Wanted, то и не нужно ничего добавлять...

**Comment by 0pdd** [comment]
@DronMDF the puzzle [#233](https://github.com/DronMDF/zold-lazy-node/issues/233) is still not solved.
