### ISSUE TITLE
Майнинг

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/zold-lazy-node#36]
Я так полагаю, что будет отдельная утилита, которая будет решать все сервисные вопросы.
И одной из функций будет майнинг.

Что-то типа того.

zln 1.2.3.4:80 mine

Алгоритм работы простой:
1. GET /
2. mine(reply['mining'])
3. post result.

В теории можно делать майнинг короткими чанками, переодически делая GET.
Потому что сервер можейт уйти вперед.
Ну где-то раз в секунду наверное нормально... Или немного реже.

**Comment by 0pdd** [comment]
@DronMDF the only puzzle [#43](https://github.com/DronMDF/zold-lazy-node/issues/43) is solved here.
