### ISSUE TITLE
GET /remotes

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/zold-lazy-node#4]
Заголовок: Content-Type , Content-Length , and X-Zold-Version

```
{
  "version": "0.13.5" ,
  "all": [
    { "host": "b2.zold.io" , "port": 4096, "score": 0 },
    { "host": "b1.zold.io" , "port": 80, "score": 0 }
   ]
}
```

**Comment by 0pdd** [comment]
@DronMDF the puzzle [#32](https://github.com/DronMDF/zold-lazy-node/issues/32) is still not solved.

**Comment by 0pdd** [comment]
@DronMDF the only puzzle [#32](https://github.com/DronMDF/zold-lazy-node/issues/32) is solved here.
