### ISSUE TITLE
app.py:109-110: Необходимо проверять содержимое запроса и...

### ISSUE THREAD

**Issue by 0pdd** [DronMDF/zold-lazy-node#48]
The puzzle `7-2bf15792` from #7 has to be resolved:

https://github.com/DronMDF/zold-lazy-node/blob/62b765ce8038d2d212628b5c3d47f0d44af9a8ba/node/app.py#L109-L110

The puzzle was created by aatsurkan on 26-Jun-18. 

Estimate: 0 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by DronMDF** [comment]
Вот у меня есть кусок кода с проверкой сигнатур...

```python3
import time

from Crypto.PublicKey import RSA
from Crypto.Signature import PKCS1_v1_5
from Crypto.Hash import SHA256

import base64

key = RSA.importKey(open('key').read())
pubkey = RSA.importKey(open('key.pub').read())

print(key.publickey().exportKey("PEM").decode('ascii'))
print(pubkey.exportKey("PEM").decode('ascii'))

message = 'Hello RSA'
h = SHA256.new(message.encode('ascii'))

signer = PKCS1_v1_5.new(key)
signature = signer.sign(h)
print(base64.b64encode(signature))

verifier = PKCS1_v1_5.new(pubkey)

if not verifier.verify(h, signature):
     print("NO")
```

Для того, чтобы заработало нужно сгенерировать пару ключей. key, key.pub

**Comment by 0pdd** [comment]
The puzzle `7-2bf15792` has disappeared from the source code, that's why I closed this issue.
