### ISSUE TITLE
при получении нового суффикса через Score необходимо проверять, что этот суффикс подходит. 

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/zold-lazy-node#54]
И привязать его к соответствующей Score.

**Comment by 0pdd** [comment]
@DronMDF 2 puzzles [#64](https://github.com/DronMDF/zold-lazy-node/issues/64), [#65](https://github.com/DronMDF/zold-lazy-node/issues/65) are still not solved.

**Comment by 0pdd** [comment]
@DronMDF the puzzle [#65](https://github.com/DronMDF/zold-lazy-node/issues/65) is still not solved; solved: [#64](https://github.com/DronMDF/zold-lazy-node/issues/64).

**Comment by 0pdd** [comment]
@DronMDF the puzzle [#84](https://github.com/DronMDF/zold-lazy-node/issues/84) is still not solved; solved: [#64](https://github.com/DronMDF/zold-lazy-node/issues/64), [#65](https://github.com/DronMDF/zold-lazy-node/issues/65).
