### ISSUE TITLE
GET /wallet/<id>

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/zold-lazy-node#6]
Выдает реплай следующего содержимого:

```
{
  "version": "0.6.1" ,
  "body": "..."
}
```

**Comment by 0pdd** [comment]
@DronMDF the puzzle [#28](https://github.com/DronMDF/zold-lazy-node/issues/28) is still not solved.

**Comment by 0pdd** [comment]
@DronMDF the only puzzle [#28](https://github.com/DronMDF/zold-lazy-node/issues/28) is solved here.
