### ISSUE TITLE
Необходимо удалять из БД Scores, которые истекли

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/zold-lazy-node#66]
Score действует сутки.

**Comment by 0pdd** [comment]
@DronMDF 3 puzzles [#79](https://github.com/DronMDF/zold-lazy-node/issues/79), [#80](https://github.com/DronMDF/zold-lazy-node/issues/80), [#81](https://github.com/DronMDF/zold-lazy-node/issues/81) are still not solved.

**Comment by 0pdd** [comment]
@DronMDF 2 puzzles [#79](https://github.com/DronMDF/zold-lazy-node/issues/79), [#81](https://github.com/DronMDF/zold-lazy-node/issues/81) are still not solved; solved: [#80](https://github.com/DronMDF/zold-lazy-node/issues/80).

**Comment by 0pdd** [comment]
@DronMDF 2 puzzles [#79](https://github.com/DronMDF/zold-lazy-node/issues/79), [#86](https://github.com/DronMDF/zold-lazy-node/issues/86) are still not solved; solved: [#80](https://github.com/DronMDF/zold-lazy-node/issues/80), [#81](https://github.com/DronMDF/zold-lazy-node/issues/81).

**Comment by DronMDF** [comment]
Эта задача решена на фронтенде.
Мы выдаем наружу только актуальные score.
Несколько нам важно сичтить список БД? На данный момент совсем не важно.

**Comment by DronMDF** [comment]
#79 заменяет этот ишью.
Этот не нужен.
