### ISSUE TITLE
PUT /wallet должен в ответе возвращать score и версию ПО

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/zold-lazy-node#68]
Пример реплая:
```json
{
    "score": "......",
    "version": "....."
}
```

И на данный момент клиент рассчитывает, что успешный запрос вернет статус 200.
А мы в соответствии с WP возвращаем 202

**Comment by 0pdd** [comment]
@DronMDF 2 puzzles [#72](https://github.com/DronMDF/zold-lazy-node/issues/72), [#73](https://github.com/DronMDF/zold-lazy-node/issues/73) are still not solved.
