### ISSUE TITLE
Сервер должен аннонсировать себя через запросы к другим серверам.

### ISSUE THREAD

**Issue by DronMDF** [DronMDF/zold-lazy-node#88]
В которые включено поле в заголовке: X-Zold-Score

Но у меня еще вообще нет запросов к другим серверам... Надо обдумать.

**Comment by DronMDF** [comment]
Как вариант мне видится следующее:
Консольная утилита с определенной переодичностью (к примеру 1 минута) берет кошелек, и сверяет его содержимое с рандомным сервером из списка ремотов. Если содержимое сходится - или сервер предлагает более свежее кошелек считается распространенным.

Если на удаленном сервере обнаруживается более свежая версия кошелька - его можно принять сразу. (всмысле залить на сервер).

Вторым шагом можно найти самый нераспространенный кошелек и залить его на случайно выбранный сервер.

Анонсирование происходит похоже при любом запросе к другому серверу. Так что можно начать с вытягивания.

Паралельно можно вести рейтинг удаленных серверов, на предмет отзывчивости, обновлять их Score. И срок действия score, тоже надо хранить. Чтобы старые сервера не маячили. Но это уже другая тема.

**Comment by 0pdd** [comment]
@DronMDF the puzzle [#127](https://github.com/DronMDF/zold-lazy-node/issues/127) is still not solved.
